ukumpcore/urls.py
from django.conf.urls import url
from django.contrib import admin

from ukumpcore.linebot_handler import linebot_handler
from ukumpcore import linelogin_handler
from patient import views as patient_view
from customer import views as customer_view

urlpatterns = [
    url(r'^kami/login/$', linelogin_handler.admin_login),
    url(r'^kami/', admin.site.urls),

    url(r'^customer/association/(?P<role>[a-z]+)?$', customer_view.LineAssociation, name='line_association'),
    url(r'^customer/feedback', customer_view.form_feedback, name='customer_feedback'),

    # 緊急通報
    url(r'^patient/(?P<patient_id>[0-9]+)/emergency', patient_view.emergency, name='patient_emergency'),

    # 檢視/填寫日報表
    url(r'^patient/(?P<patient_id>[0-9]+)/summary/$', patient_view.summary, name='patient_summary'),

    # 檢視日報表清單
    # url(r'^patient/daily_reports$', patient_view.daily_reports, name='patient_dairly_reports'),

    # 檢視日報表
    url(r'^patient/(?P<patient_id>[0-9]+)/report/daily/(?P<date>\d{4}-\d{2}-\d{2})/(?P<period>\d{2})/$', patient_view.DailyReport, name='patient_daily_report'),
    url(r'^patients/form/postback', patient_view.form_postback),

    # 卡片
    url(r'^patient/card/(?P<card>\d{1})/$', patient_view.dairy_card, name='patient_card'),
    url(r'^patient/card/(?P<card>\d{1})/html$', patient_view.daily_card_html, name='patient_card_html'),

    url(r'^integrations/linebot$', linebot_handler),
    url(r'^integrations/linebot/nav/([a-z_-]{1,30})', linelogin_handler.nav, name='line_nav'),
    url(r'^integrations/linebot/login/final$', linelogin_handler.final, name='linelogin_final'),
    url(r'^integrations/linebot/login$', linelogin_handler.login, name='linelogin'),
]

customer/models.py
from django.contrib.postgres.fields import JSONField
from django.db.models.functions import Now
from django.db import models
import json


class LineMessageManager(models.Manager):
    def padding_message(self):
        return self.get_queryset().filter(scheduled_at__lt=Now())


class Profile(models.Model):
    class Meta:
        db_table = "customer"

    name = models.TextField()
    phone = models.TextField(null=True, blank=True)
    profile = JSONField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "%s#客戶 %s" % (self.id, self.name)

    def push_raw_message(self, raw_data, scheduled_at=Now()):
        LineMessageQueue(customer=self, scheduled_at=scheduled_at, message=raw_data).save()

    def push_message(self, message, scheduled_at=Now()):
        LineMessageQueue(customer=self, scheduled_at=scheduled_at, message=json.dumps({'M': 't', 'text': message})).save()


class LineBotIntegration(models.Model):
    class Meta:
        db_table = "customer_linebot_integration"

    lineid = models.TextField(primary_key=True)
    customer = models.ForeignKey(Profile, on_delete=models.CASCADE)


class LineMessageQueue(models.Model):
    class Meta:
        db_table = "customer_message_queue"

    objects = LineMessageManager()

    customer = models.ForeignKey(Profile, on_delete=models.CASCADE)
    scheduled_at = models.DateTimeField()
    message = models.TextField()

    def get_line_ids(self):
        return self.customer.linebotintegration_set.values_list('lineid', flat=True)

patient/models.py
from django.contrib.postgres.fields import DateTimeRangeField
from django.contrib.postgres.fields import JSONField
from django.db.models.functions import Cast, TruncDate, Lower
from django.utils.timezone import localdate, timedelta
# from django.db.models import signals
# from django.dispatch import receiver
from django.conf import settings
from django.db import models

from care.models import CourseQuestion

dt_field = models.DateTimeField()


class ReportManager(models.Manager):
    def today(self):
        return self.get_queryset().extra(where=(
            "(report_date = (current_timestamp AT TIME ZONE 'Asia/Taipei')::Date)",)
        ).order_by("report_period")

    def yesterday(self):
        return self.get_queryset().extra(where=(
            "(report_date = ((current_timestamp - interval '1 day') AT TIME ZONE 'Asia/Taipei')::Date)",)
        ).order_by("report_period")


class Profile(models.Model):
    class Meta:
        db_table = "patient_profile"

    name = models.TextField()
    birthday = models.DateField(null=True, blank=True)
    extend = JSONField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    customers = models.ManyToManyField(to='customer.Profile',
                                       through='Guardian',
                                       through_fields=('patient', 'customer'),
                                       related_name='patients')
    managers = models.ManyToManyField(to='employee.Profile',
                                      through='Manager',
                                      through_fields=('patient', 'employee'),
                                      related_name='patients')

    def __str__(self):
        return "%s#個案 %s" % (self.id, self.name)


class DummyNote(models.Model):
    class Meta:
        db_table = "patient_note"

    patient = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.TextField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)


class Guardian(models.Model):
    class Meta:
        db_table = "patient_guardian"
        unique_together = ('patient', 'customer')

    patient = models.ForeignKey(Profile, on_delete=models.CASCADE)
    customer = models.ForeignKey("customer.Profile", on_delete=models.CASCADE)
    master = models.BooleanField(null=False, default=False)
    subscribe = models.BooleanField(null=False, default=True)
    relation = models.TextField(null=True)


class Manager(models.Model):
    class Meta:
        db_table = "patient_manager"
        unique_together = ('patient', 'employee')

    patient = models.ForeignKey(Profile, on_delete=models.CASCADE)
    employee = models.ForeignKey("employee.Profile", on_delete=models.CASCADE)
    relation = models.TextField()


class CourseSchedule(models.Model):
    class Meta:
        db_table = "patient_course_table"

    patient = models.ForeignKey(Profile, related_name="course_schedule", on_delete=models.CASCADE)
    table = models.ForeignKey("care.Course", on_delete=models.CASCADE)
    weekly_mask = models.IntegerField()

    def __str__(self):
        return "%s#個案課程 %s" % (self.id, self.table.name)


class ScheduleManager(models.Manager):
    def with_date(self):
        return self.get_queryset().annotate(date=TruncDate(Cast(Lower('schedule'), dt_field)))

    def schedule_at(self, date):
        return self.get_queryset().extra(where=(
            "(LOWER(schedule) AT TIME ZONE 'Asia/Taipei')::Date = ('%s')::Date" % (date.strftime('%Y-%m-%d'), ),))

    def today_schedule(self):
        return self.get_queryset().extra(where=(
            "(LOWER(schedule) AT TIME ZONE 'Asia/Taipei')::Date = (current_timestamp AT TIME ZONE 'Asia/Taipei')::Date",))

    def scheduled_at(self, date):
        return self.get_queryset().annotate(date=TruncDate(Cast(Lower('schedule'), dt_field))).filter(date=date)

    def today(self):
        return self.scheduled_at(localdate())

    def tomorrow(self):
        return self.scheduled_at(localdate() + timedelta(days=1))


class NursingSchedule(models.Model):
    class Meta:
        db_table = "patient_nursing_schedule"

    objects = ScheduleManager()

    patient = models.ForeignKey(Profile, related_name='nursing_schedule', on_delete=models.CASCADE)
    employee = models.ForeignKey("employee.Profile", related_name='nursing_schedule', on_delete=models.CASCADE)
    schedule = DateTimeRangeField()
    flow_control = models.DateTimeField(null=True)

    def today_courses(self):
        return self.patient.course_schedule.extra(
            where=("(weekly_mask & (1 << EXTRACT(DOW FROM current_timestamp AT TIME ZONE 'Asia/Taipei')::int)) > 0", ))

    def fetch_next_question(self):
        courses_id = self.patient.course_schedule.extra(
            where=("(weekly_mask & (1 << EXTRACT(DOW FROM current_timestamp AT TIME ZONE 'Asia/Taipei')::int)) > 0", )
        ).values_list('table_id', flat=True)
        items = CourseQuestion.objects.filter(table_id__in=courses_id).extra(
            where=("care_course_question.scheduled_at > (SELECT (flow_control AT TIME ZONE 'Asia/Taipei')::Time FROM patient_nursing_schedule WHERE id = %i)" % self.id,
                   "care_course_question.scheduled_at <= (SELECT (UPPER(schedule) AT TIME ZONE 'Asia/Taipei')::Time FROM patient_nursing_schedule WHERE id = %i)" % self.id)
        ).select_related("question").order_by('scheduled_at')
        t = None
        for it in items:
            if not t:
                yield it
                t = it.scheduled_at
            elif it.scheduled_at == t:
                yield it
            else:
                return

    def __str__(self):
        return "%s#班表 %s/%s@%s" % (self.id, self.patient, self.employee, self.schedule.lower)


class CareDailyReport(models.Model):
    class Meta:
        db_table = 'patient_daily_report'
        unique_together = ('patient', 'report_date', 'report_period')

    objects = ReportManager()
    patient = models.ForeignKey(Profile, on_delete=models.CASCADE)
    form_id = models.TextField(null=True, blank=True)
    report_date = models.DateField()
    report_period = models.IntegerField()
    report = JSONField()

    filled_by = models.ForeignKey("employee.Profile", related_name="+", on_delete=models.CASCADE)
    reviewed_by = models.ForeignKey("employee.Profile", related_name="+", null=True, on_delete=models.CASCADE)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def get_report(cls, patient_id, report_date, report_period):
        return cls.objects.filter(patient_id=patient_id, report_date=report_date, report_period=report_period).first()

    @classmethod
    def get_form_id(cls, patient_id, employee_id, report_date):
        schedule = NursingSchedule.objects.schedule_at(report_date).filter(patient_id=patient_id, employee_id=employee_id)
        if len(schedule) != 1:
            raise RuntimeError('找到重複的排程，請聯絡系統管理員。')
        form_ids = schedule.first().today_courses().exclude(table__report__isnull=True).values_list('table__report', flat=True)
        if form_ids.count() == 0:
            raise RuntimeError('沒有可用的報表，請聯絡系統管理員。')
        elif form_ids.count() > 1:
            raise RuntimeError('找到重複的報表，請聯絡系統管理員。')
        return form_ids.first()

    @classmethod
    def is_manager(cls, employee_id, patient_id):
        return employee_id and Manager.objects.filter(patient_id=patient_id, employee_id=employee_id).exists()

    @classmethod
    def is_nurse(cls, employee_id, patient_id, date):
        return employee_id and NursingSchedule.objects.schedule_at(date).filter(patient_id=patient_id, employee_id=employee_id)

    @classmethod
    def is_guardian(cls, customer_id, patient_id):
        return customer_id and Guardian.objects.filter(patient_id=patient_id, customer_id=customer_id).exists()

    @property
    def form_name(self):
        return settings.CARE_REPORTS.get(self.form_id, {}).get('label', '無名稱日報表')


class CareHistory(models.Model):
    class Meta:
        db_table = "patient_care_history"

    patient = models.ForeignKey(Profile, on_delete=models.CASCADE)
    question = models.ForeignKey("care.Question", on_delete=models.CASCADE)
    answer_int = models.IntegerField(null=True)
    answer_str = models.TextField(null=True)
    routine = models.BooleanField()
    employee = models.ForeignKey("employee.Profile", related_name='+', null=True, on_delete=models.CASCADE)
    scheduled_at = models.DateField()
    answered_at = models.DateTimeField(auto_now_add=True)


class LinebotDummyLog(models.Model):
    class Meta:
        db_table = 'linebot_dummy_log'

    lineid = models.TextField()
    catalog = models.TextField()
    payload = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def append(cls, userid, catalog, payload):
        LinebotDummyLog(lineid=userid, catalog=catalog, payload=payload).save()


class UkumpGlobal(models.Model):
    class Meta:
        db_table = "ukump_global"

    key = models.CharField(max_length=50, primary_key=True)
    value = JSONField()

customer/templates/customer/association.html
{% extends 'base.html' %}
{% block page_title %}註冊{% endblock %}

{% block navigation %}
<div class="container">
    <h3>請選擇身份</h3>
    <hr />
</div>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 1em;">
    <div style='margin: 1em'>
        <a href="{% url 'line_association' 'customer' %}" class="btn btn-lg btn-primary"
            style="width: 100%; padding-top: 10%; padding-bottom: 10%;">客戶直接註冊</a>
    </div>
    <div style='margin: 1em'>
        <a href="{% url 'line_association' 'guest' %}" class="btn btn-lg btn-info"
            style="width: 100%; padding-top: 10%; padding-bottom: 10%;">使用邀請碼註冊</a>
    </div>
    <div class="text-center" style="margin: 1em;">
        <a href="{% url 'line_association' 'employee' %}">照服員</a>
    </div>
</div>
{% endblock %}

customer/templates/customer/association_completed.html
{% extends 'base.html' %}
{% block page_title %}註冊{% endblock %}
{% block navigation %}

<div class="container">
    <h3>註冊完成</h3>
    <hr />
</div>
{% endblock %}

{% block content %}
<style>
form label, form input, form.button {
    margin-right: 1em;
}
</style>
<div class="container" style="margin-top: 1em;">
    <h5>基本資料</h5>
    <div>身份：{% if role == "employee" %}工作人員{% else %}家屬{% endif %}</div>
    <div>姓名：{{ source.name }}</div>
    <div>電子郵件：{{ source.profile.email }}</div>
    <div>聯絡電話：{% if role == "employee" %}{{ source.profile.phone }}{% else %}{{ source.phone }}{% endif %}</div>
    <hr />
    {% if role == "customer" %}

    <h5>個案</h5>
    {% for guardian in source.guardian_set.all %}
        <div style="margin: 1em 0 1em 0;">{{ guardian.patient.name }} - {{ guardian.relation }}</div>
    {% endfor %}
    <hr />

    {% endif %}
    <h5>LINE 資料</h5>
    {% for profile in line_profiles %}
        {% if 'displayName' in profile %}
        <div style="margin: 1em 0 1em 0;">
            <div class="row">
                <div class='col-2'>
                    <img src="{{ profile.pictureUrl }}" class="img-thumbnail" />
                </div>
                <div class='col-10'>
                    <div>{{ profile.displayName }}</div>
                    <small>顯示狀態 {{ profile.statusMessage }}</small><br />
                    <small>LineID 識別碼 {{ profile.userId }}</small>
                </div>
            </div>
        </div>
        {% else %}
        <div style="margin: 1em 0 1em 0;">無法處 LINE 識別碼 '{{ profile.userId }}'</div>
        {% endif %}
    {% endfor %}
</div>
{% endblock %}

customer/templates/customer/association_customer.html
{% extends 'base.html' %}
{% block page_title %}註冊{% endblock %}

{% block navigation %}
<div class="container">
    <h3>客戶註冊</h3>
    <hr />
</div>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 1em;">
    <form method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>電話號碼</label>
            <input type="text" name="pnum" class="form-control" placeholder="電話號碼" value="{{ request.POST.pnum }}" required />
        </div>
        {% if confirm %}
        <div class="form-group">
            <label>驗證碼</label>
            <input type="text" name="confirm-code" class="form-control" placeholder="驗證碼" />
        </div>
        {% endif %}
        {% if confirm %}
        <div class="row">
            <div class="col-6">
                <button class="btn btn-primary" type="submit" name="submit" value="confirm">確認</button>
            </div>
            <div class="col-6 text-right">
                <button class="btn btn-danger" type="submit" name="submit" value="check">重新發送確認碼</button>
            </div>
        </div>
        {% else %}
        <div class="form-group">
            <button class="btn btn-primary" type="submit" name="submit" value="check">繼續</button>
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

customer/templates/customer/association_employee.html
{% extends 'base.html' %}
{% block page_title %}註冊{% endblock %}

{% block navigation %}
<div class="container">
    <h3>照服員註冊</h3>
    <hr />
</div>
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 1em;">
    <form method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>電話號碼</label>
            <input type="text" name="pnum" class="form-control" placeholder="電話號碼" value="{{ request.POST.pnum }}" required />
        </div>
        {% if confirm %}
        <div class="form-group">
            <label>驗證碼</label>
            <input type="text" name="confirm-code" class="form-control" placeholder="驗證碼" />
        </div>
        {% endif %}
        {% if confirm %}
        <div class="row">
            <div class="col-6">
                <button class="btn btn-primary" type="submit" name="submit" value="confirm">確認</button>
            </div>
            <div class="col-6 text-right">
                <button class="btn btn-danger" type="submit" name="submit" value="check">重新發送確認碼</button>
            </div>
        </div>
        {% else %}
        <div class="form-group">
            <button class="btn btn-primary" type="submit" name="submit" value="check">繼續</button>
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}

customer/templates/customer/association_guest.html
{% extends 'base.html' %}
{% block page_title %}註冊{% endblock %}
{% block content %}
<div class="container" style="margin-top: 1em;">
    <h3>客戶註冊</h3>
    <hr />
    <form method='post'>
        {% csrf_token %}
        <div class="form-group">
            <label>姓名</label>
            <input type="text" name="cname" class="form-control" placeholder="姓名" value="{{ request.POST.cname }}" required />
        </div>
        <div class="form-group">
            <label>電話號碼</label>
            <input type="text" name="cnum" class="form-control" placeholder="電話號碼" value="{{ request.POST.cnum }}" required />
        </div>
        <div class="form-group">
            <label>電子郵件</label>
            <input type="email" name="cemail" class="form-control" placeholder="電子郵件" value="{{ request.POST.cemail }}" required />
        </div>
        <div class="form-group">
            <label>與個案關係</label>
            <input type="text" name="crel" class="form-control" placeholder="父子, 兄弟.. 等等" value="{{ request.POST.crel }}" required />
        </div>
        <div class="form-group">
            <label>邀請碼</label>
            <input type="text" name="cinv" class="form-control" placeholder="由照護經理提供邀請碼" value="{{ request.POST.cinv }}" required />
        </div>
        {% if confirm %}
        <div class="form-group">
            <label>驗證碼</label>
            <input type="text" name="confirm-code" class="form-control" placeholder="驗證碼" />
        </div>
        {% endif %}
        {% if confirm %}
        <div class="row">
            <div class="col-6">
                <button class="btn btn-primary" type="submit" name="submit" value="confirm">確認</button>
            </div>
            <div class="col-6 text-right">
                <button class="btn btn-danger" type="submit" name="submit" value="check">重新發送確認碼</button>
            </div>
        </div>
        {% else %}
        <div class="form-group">
            <button class="btn btn-primary" type="submit" name="submit" value="check">繼續</button>
        </div>
        {% endif %}
    </form>
</div>
{% endblock %}